name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete --exclude ".git/*"

      - name: Invalidate CloudFront: Dashboard
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DASHBOARD_DIST_ID }} \
            --paths "/dashboard.html"

      - name: Invalidate CloudFront: Main Site
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.MAIN_DIST_ID }} \
            --paths "/index.html"
